version: "3.7"

services:
  myapp:
    build:
      context: ./myapp
      dockerfile: Dockerfile
      target: ${TARGET}
    image: myapp:local
    container_name: myapp
    ports:
      - "8080:80"
